export const clean = (masterVarList) => {
	console.log(masterVarList);

	var dict = {};

	for (let idx = 0; idx <= masterVarList.length - 1; idx++) {
		var tmpvar = masterVarList[idx];

		if (dict.hasOwnProperty(tmpvar.id)) {
			var tmplist = dict[tmpvar.id];
			tmplist.push(tmpvar);
			dict[tmpvar.id] = tmplist;
		} else {
			var tmplist = [tmpvar];
			dict[tmpvar.id] = tmplist;
		}
	}

	var tmplist = [];

	for (let key in dict) {
		var tmpdict = {};
		tmpdict["id"] = key;
		tmpdict["lake"] = dict[key];

		tmplist.push(tmpdict);
	}

	var final = [];

	for (let jdx = 0; jdx <= tmplist.length - 1; jdx++) {
		var voi = tmplist[jdx];
		var tmpid = voi.id;
		var tmpdata = voi.lake;

		/**
            i want
            {
                id: thing
                lake: [
                    {
                        name: "Farms",
                        desc:
                        report
                        is_invalid
                        unit
                    }, 

                ]
            }
        */

		// then we need to flatten
		var tmplake = [];

		for (let kdx = 0; kdx <= tmpdata.length - 1; kdx++) {
			var ship = {};

			ship["name"] = tmpdata[kdx].name;
			ship["description"] = tmpdata[kdx].description;
			ship["report"] = tmpdata[kdx].report;
			ship["unit"] = tmpdata[kdx].unit;
			ship["is_invalid"] = tmpdata[kdx].is_invalid;

			tmplake.push(ship);
		}

		var finaltmp = {};
		finaltmp["id"] = tmpid;
		finaltmp["lake"] = tmplake;

		final.push(finaltmp);
	}

	return final;
};

export const masterVarList = [
	{
		id: "kount",
		name: "Farms",
		description: "Estimated number of farms.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farms",
		description: "Estimated number of farms.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Number",
	},
	{
		id: "igovtt",
		name: "All government payments",
		description:
			"Total government payments include direct payments, countercyclical-type payments, marketing loan benefits, conservation payments, and other payments.",
		sequence: 10,
		is_invalid: false,
		group: 5,
		level: 1,
		report: "Government Payments",
		unit: "1,000 Dollars",
	},
	{
		id: "kntdp",
		name: "Farms",
		description: "Estimated number of farms receiving a fixed direct payment.",
		sequence: 10,
		is_invalid: false,
		group: 12,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farms",
		description: "Estimated number of farms.",
		sequence: 10,
		is_invalid: false,
		group: 1,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farm Households (HH)",
		description: "Estimated number of farm households.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Income",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farms",
		description: "Estimated number of farms.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Balance Sheet",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farms",
		description: "Estimated number of farms.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Income Statement",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farms",
		description: "Estimated number of farms.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Number",
	},
	{
		id: "kount",
		name: "Farm Households (HH)",
		description: "Estimated number of farm households.",
		sequence: 10,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Balance Sheet",
		unit: "Number",
	},
	{
		id: "igcfi",
		name: "Gross cash farm income",
		description:
			"For farms participating in government programs, gross cash farm income is the total amount of cash received by the farm operation from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "frcrnum",
		name: "Current ratio",
		description:
			"The current ratio, one measure of liquidity, indicates the extent to which the liquidation of current assets would be sufficient to cover current liabilities.  The value of this ratio will vary throughout the production cycle and by type of business.  Greater liquidity is indicated by higher ratio values.",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Ratio",
	},
	{
		id: "vprodtot",
		name: "Total value of production",
		description: "Total value of production",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "1,000 Dollars",
	},
	{
		id: "igovccpt",
		name: "Countercyclical-type payments",
		description:
			"Countercyclical-type payments are made to producers of eligible crops, based on historical production of program crops, but the payment rates depend on market prices.  The countercyclical payment (CCP) program that began with the 2002 Farm Act ended in 2014, as did the countercyclical Average Crop Revenue Election (ACRE) program. Two new countercyclical-type programs have since been established: the Price Loss Coverage (PLC) program and the Agriculture Risk Coverage (ARC) program.",
		sequence: 20,
		is_invalid: false,
		group: 5,
		level: 1,
		report: "Government Payments",
		unit: "1,000 Dollars",
	},
	{
		id: "kountg",
		name: "Farms",
		description: "Number of farms receiving government payments.",
		sequence: 20,
		is_invalid: false,
		group: 3,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "hhasset",
		name: "Total operator household assets",
		description:
			"The estimated market value of household assets reported by the farm operator including cash, checking, CD's, Money Market accounts, IRA, 401K, Keogh and other retirement accounts, corporate stock, mutual funds, value of the operator's dwelling if not owned by the farm, real estate, business not part of the farm, and household vehicles.",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "atot",
		name: "Farm assets",
		description:
			"Total assets represents the survey respondents' estimated market value on December 31 of all capital assets owned by the farm operation.  For operations where the operator dwelling is considered part of the farm and located on the farm, the value of the dwelling is included.",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "kdebt",
		name: "Number of farms with debt",
		description: "Number of farms that reported notes payable on December 31.",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Number",
	},
	{
		id: "kntccp",
		name: "Farms",
		description:
			"Number of farms receiving a countercyclical-type payment that are a function of commodity prices.",
		sequence: 20,
		is_invalid: false,
		group: 13,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "tothhi",
		name: "Total operator household income (HHI)",
		description:
			"Total income for the farm operator household consists of income from the farm business, income from other farming activities, and income from earned and unearned off-farm sources.",
		sequence: 20,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Income",
		unit: "Dollars per HH",
	},
	{
		id: "actot",
		name: "Assets: Current",
		description:
			"Current assets are those assets that will be realized in cash, sold or consumed in the production process within one year.",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "iliv",
		name: "Livestock income",
		description:
			"The value of all livestock and poultry sold from the farm operation net of any marketing charges.  All sales of livestock through marketing contracts or payments received from prior years' contracts are also included.  For integrated operations, which do not sell the livestock but pass them on to another phase of the operation, an estimate of the value of the livestock moving through the operation is captured as sales.",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "igcfi",
		name: "Gross cash farm income",
		description:
			"For farms participating in government programs, gross cash farm income is the total amount of cash received by the farm operation from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "kntmlb",
		name: "Farms",
		description:
			"Estimated number of farms receiving a marketing loan benefit.",
		sequence: 30,
		is_invalid: false,
		group: 14,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "farmhhi",
		name: "Total operator household income from farming activities",
		description:
			"Total income for the farm operator household consists of income from the farm business, income from other farming activities, and income from earned and unearned off-farm sources.",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Income",
		unit: "Dollars per HH",
	},
	{
		id: "frwcnum",
		name: "Working capital-to-expense ratio",
		description:
			"Working capital is calculated by subtracting total current liabilities from total current farm assets. The ratio is calculated as working capital divided by total cash operating expenses.",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "tacres",
		name: "Total acres operated",
		description: "Total acres operated",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "1,000 Acres",
	},
	{
		id: "igovdpt",
		name: "Direct payments",
		description:
			"Direct payments are payments made to producers based on eligible historical acreage of program crops and historical yields. Between 1996 and 2001, fixed payments were provided as production flexibility contract (PFC) payments before being redesigned in the 2002 Farm Act as direct payments. These direct payments ended as a result of the Agricultural Act of 2014.",
		sequence: 30,
		is_invalid: false,
		group: 5,
		level: 1,
		report: "Government Payments",
		unit: "1,000 Dollars",
	},
	{
		id: "kountn",
		name: "Farms",
		description: "Number of farms not receiving government payments.",
		sequence: 30,
		is_invalid: false,
		group: 2,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "fasst",
		name: "Total operator household assets: Farm",
		description:
			"Farm operator household's share of total farm business assets. Total assets represents the survey respondents' estimated market value on December 31 of all capital assets owned by the farm operation. For operations where the operator dwelling is considered part of the farm and located on the farm, the value of the dwelling is included.",
		sequence: 30,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "frdanum",
		name: "Debt/asset ratio",
		description:
			"The debt/asset ratio is defined as total liabilities divided by total assets. This ratio indicates the risk associated with the operation's financial structure.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "acres",
		name: "Acres operated per farm",
		description:
			"The number of acres owned by the operation plus the number of acres rented from others minus the number of acres rented to others.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Acres",
	},
	{
		id: "drinc",
		name: "Income for debt coverage",
		description:
			"Calculated as net farm income plus interest on capital debt. Indicates the funds available for debt repayment.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "conspayt",
		name: "Conservation payments",
		description:
			"Conservation program payments are payments made to producers that include land-retirement programs where agricultural production cannot occur on land enrolled in the program as well as working-land programs that provide payments for maintaining or adopting resource conservation practices on land in production.",
		sequence: 40,
		is_invalid: false,
		group: 5,
		level: 1,
		report: "Government Payments",
		unit: "1,000 Dollars",
	},
	{
		id: "totofi",
		name: "Total operator household income from off-farm sources",
		description:
			"Off-farm income can be classified as earned or unearned. Earned income sources are those that require a household member to allocate their labor or management time to the activity. This includes wages and salaries and off-farm self-employment income. Unearned income sources are passive or transfer income, such as from interest, dividends, private pensions, Social Security, veterans' benefits, and other public programs.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Income",
		unit: "Dollars per HH",
	},
	{
		id: "acliv",
		name: "Assets: Livestock inventory",
		description:
			"The market value of livestock and poultry on hand that are owned by the farm operation, excluding animals held for breeding purposes.  Animals that are owned for pleasure are not included.  Livestock or poultry that is owned by the operation, but being raised by another operation under a contract are included.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "icrop",
		name: "Crop sales",
		description:
			"The amount received from cash sales and marketing or forward contracts for all crops plus the difference between Commodity Credit Corporation crop placements and redemptions.  Payments received for crops produced in previous years or delivered under prior year's marketing contracts are included.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "igovt",
		name: "Average payments per farm",
		description: "Government payments received across all programs, all farms.",
		sequence: 40,
		is_invalid: false,
		group: 16,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "kntcnsv",
		name: "Farms",
		description: "Number of farms receiving a conservation program payment.",
		sequence: 40,
		is_invalid: false,
		group: 7,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "nfasst",
		name: "Total operator household assets: Non-farm",
		description:
			"Estimated market value of farm operator's household assets on December 31.",
		sequence: 40,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "accrop",
		name: "Assets: Crop inventory",
		description:
			"The market value of all crops owned by the operation whether stored on or off the farm. Crops under Commodity Credit Corporation loans are not included; however, crops in storage which have been redeemed from CCC loan are included.",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "igovt",
		name: "Government payments",
		description:
			"Gross value of direct government payments received by farm operations during the calendar year. Programs for which payments are received include: direct payments, counter-cyclical payments, loan deficiency payments (LDPs), marketing loan gains, peanut quota buyout program, milk income loss contract payments, disaster payments, conservation reserve program (CRP), wetlands reserve program (WRP), environmental quality incentive program (EQIP), and all other Federal and State programs.",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "ten1",
		name: "Farms by tenure: Full owner",
		description:
			"The share of farms in the report column that own all of the land operated.",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "drintp",
		name: "Principal/interest payments",
		description:
			"Reported farm business interest payments and estimated principal payments.",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "igovtg2",
		name: "Average payments per farm",
		description:
			"Government payments received across all programs, all program participants.",
		sequence: 50,
		is_invalid: false,
		group: 17,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "mlbt",
		name: "Marketing loan benefits payments",
		description:
			"Marketing loan benefits, including Loan Deficiency Program payments, Marketing Loan Gains, and Certificate Exchange Gains, are payments made to farmers based on market prices for eligible commodities falling below program target prices. Marketing assistance loan programs are based on current production and tend to provide payments when market prices fall below target levels.",
		sequence: 50,
		is_invalid: false,
		group: 5,
		level: 1,
		report: "Government Payments",
		unit: "1,000 Dollars",
	},
	{
		id: "fmhhtot",
		name: "Percent of U.S. average household income",
		description:
			"Farm operator household income as a percentage of the U.S. Census Bureau's measure for all U.S. households (http://www.census.gov/cps/).",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Income",
		unit: "Percent",
	},
	{
		id: "frroanum",
		name: "Rate of return on assets",
		description:
			"Rate of return on assets is defined as net farm income plus interest expenses minus estimated charges for operator labor and management, divided by total assets.  This ratio reveals the returns received by the farm operator for both debt and equity capital invested.",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "kntoth",
		name: "Farms",
		description:
			"Estimated number of farms receiving other types of payments including disaster and emergency payments.",
		sequence: 50,
		is_invalid: false,
		group: 15,
		level: 1,
		report: "Government Payments",
		unit: "Number",
	},
	{
		id: "hhdebt",
		name: "Total operator household debt",
		description:
			"The amount of household debt on December 31, including mortgages on the dwelling if not owned by the farm, mortgages on other real estate, loans on businesses not part of the farm, and personal loans and credit cards.",
		sequence: 50,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "acinpt",
		name: "Assets: Purchased inputs",
		description:
			"The value of unused supplies of purchased inputs such as seed, feed, chemicals, fuels, and fertilizers.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "drdcm",
		name: "Debt coverage margin",
		description:
			"Calculated as income for debt coverage minus the amount of funds necessary for debt payment of current obligations.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "igovdp1",
		name: "Average government payment per participating farm",
		description:
			"Direct payments received by direct payment program participants.",
		sequence: 60,
		is_invalid: false,
		group: 25,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "otherpayt",
		name: "Other government program payments",
		description:
			"Other government program payments include payments from disaster relief programs and emergency payments. They tend to be temporary, as-needed Government responses to droughts, floods, and other natural disasters. We include various other programs as well, including the milk income support programs, the tobacco transition program, peanut quota buyouts, and/or all other programs not specified in ARMS questionnaires.",
		sequence: 60,
		is_invalid: false,
		group: 5,
		level: 1,
		report: "Government Payments",
		unit: "1,000 Dollars",
	},
	{
		id: "fdebt",
		name: "Total operator household debt: Farm",
		description:
			"Farm operator household's share of total farm liabilities. Total liabilities are composed of any monetary obligations of the farm operation on December 31. The amount reported includes principal due and any unpaid interest.  Debts for nonfarm purposes, even if farm or ranch asset are used as collateral, are excluded.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "iothfm",
		name: "Other farm-related income",
		description:
			"Includes income from machine-hire, custom work, livestock grazing, land rental, contract production fees, outdoor recreation, timber sales,  hedging profit or losses, insurance indemnities, cooperative patronage dividends and refunds, leasing of livestock and machinery or equipment, and any other farm-related source.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "frroenum",
		name: "Rate of return on equity",
		description:
			"Rate of return on equity equals net farm income minus estimated charges for operator labor and management, divided by net worth.  This ratio indicates the relationship between net profits and equity of the farm business.  A negative return on equity is a relative measure of financial stress.  The absolute size of the ratio roughly measures the rate at which a farm business is adding to or consuming from its own capital stock.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "ten2",
		name: "Farms by tenure: Part owner",
		description:
			"The share of farms in the report column that own some of the land operated.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "igovtn1",
		name: "Average payments per farm",
		description:
			"Government payments received across all programs, all non-participants.",
		sequence: 60,
		is_invalid: false,
		group: 18,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "agi",
		name: "Estimated Adjusted Gross Income (AGI)",
		description:
			"For 2003 - present, Estimated AGI is calculated as total income for the farm operator household less adjustments to household income including any self-employment health insurance deductions, retirement contribution deductions, and deductions for half of the self-employment tax, using data from the ARMS. For 1996-2002, the same calculation is used except that self-employment health insurance deductions and retirement contribution deductions are not included due to a lack of relevant data. See Williamson and Bawa at https://www.ers.usda.gov/publications/pub-details/?pubid=95009.",
		sequence: 60,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Income",
		unit: "Dollars per HH",
	},
	{
		id: "acgrow",
		name: "Assets: Cash invested in growing crops",
		description:
			"Represents the amount of sunk costs for cover crops or crops not yet harvested.",
		sequence: 70,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "etot",
		name: "Total cash expenses",
		description:
			"Cash expenses represent the total amount of funds paid out by the farm operation during a calendar year.  Expenses paid by landlords or parties for which a contractual agreement existed during the year are excluded from cash expenses reported for farm operations.  Marketing charges such as commissions, storage, inspection, insurance, drying, check-offs, yardage, and auction are excluded from cash expenses.",
		sequence: 70,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "ten3",
		name: "Farms by tenure: Tenant",
		description:
			"The share of farms in the report column that rent all of the land operated.",
		sequence: 70,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "fropmnum",
		name: "Operating profit margin",
		description:
			"The operating profit margin is the ratio of operating profit to gross farm income, reflecting total funds available to finance the farm's ongoing operation. The numerator, operating profit, is equal to net farm income (gross farm income minus all cash and noncash expenses minus depreciation) plus any interest expenses paid minus estimated charges for all operator and household unpaid labor and management. The denominator of the measure, gross farm income, includes gross cash farm income, annual inventory change, and any nonmoney income.",
		sequence: 70,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "drmaxpay",
		name: "Maximum loan payment",
		description:
			"Calculated as income for debt coverage divided by the minimum debt coverage ratio.",
		sequence: 70,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "igcfi",
		name: "Average gross cash farm income per farm",
		description:
			"For farms participating in government programs, gross cash farm income is the total amount of cash received by the farm operation from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 70,
		is_invalid: false,
		group: 19,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "igovccp1",
		name: "Average government payment per participating farm",
		description:
			"Countercyclical-type payments received by countercyclical-type program participants.",
		sequence: 70,
		is_invalid: false,
		group: 26,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "nfdebt",
		name: "Total operator household debt: Non-Farm",
		description:
			"Amount of debt obligations of the farm operator household on December 31.",
		sequence: 70,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "acprpins",
		name: "Assets: Prepaid insurance",
		description:
			"Outlays for insurance coverage made in the past that are not completely used up.",
		sequence: 80,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evtot",
		name: "Variable expenses",
		description:
			"Expenses incurred in the production process that vary with the quantity and prices of inputs used.",
		sequence: 80,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "frdcnum",
		name: "Term debt coverage ratio",
		description:
			"This ratio is a variant of the term debt and capital lease coverage ratio recommended by the Farm Financial Standards Council. It measures income available for debt coverage relative to required debt service payments. It is defined as net farm income plus depreciation plus interest on term debt divided by annual scheduled principal and interest payments on term debt.",
		sequence: 80,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Number of times",
	},
	{
		id: "opoc1",
		name: "Operator occupation: Farming",
		description:
			"The share of farm operators in the report column that reported farming as their primary occupation",
		sequence: 80,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "drmaxd75",
		name: "Max feasible debt (7.5%)",
		description:
			"The maximum amount of debt that can be repaid given current income. Calculated at 7.5 percent interest rate amortized over a hypothetical repayment term of 7 years.",
		sequence: 80,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "igcfig",
		name: "Average gross cash farm income per farm",
		description:
			"For farms participating in government programs, gross cash income is the total amount of cash received by the farm operation from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 80,
		is_invalid: false,
		group: 20,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "mlb2",
		name: "Average government payment per participating farm",
		description:
			"Marketing loan benefit payments received by marketing loan program participants.",
		sequence: 80,
		is_invalid: false,
		group: 27,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "hhnw",
		name: "Total Operator household net worth",
		description:
			"Total farm household assets minus total farm household debt.  Farm household wealth is derived from a variety of sources. It ranges from physical assets of both the business and household to various types of financial assets, all differing in degree of liquidity, capital certainty, and visibility.",
		sequence: 80,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "acothr",
		name: "Assets: Other",
		description:
			"The value of all stock in Federal Land Banks, Production Credit Associations, Agricultural Credit Associations, and other farm cooperatives; accounts receivable (including Government payments due); hedging account balances; certificates of deposit; checking and savings balances; and any other financial assets of the farm business.",
		sequence: 90,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "fratnum",
		name: "Asset turnover ratio",
		description:
			"The asset turnover ratio, which is calculated as the farm production value divided by total farm assets, measures the income generated per dollar of assets used in production.",
		sequence: 90,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Number of times",
	},
	{
		id: "opoc2",
		name: "Operator occupation: Something else",
		description:
			"The share of farm operators in the report column that reported something else (other than farming or retired) as their primary occupation",
		sequence: 90,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "drmaxd10",
		name: "Max feasible debt (10%)",
		description:
			"The maximum amount of debt that can be repaid given current income. Calculated at 10 percent interest rate amortized over a hypothetical repayment term of 7 years.",
		sequence: 90,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "conspay2",
		name: "Average government payment per participating farm",
		description:
			"Conservation payments received by conservation program participants.",
		sequence: 90,
		is_invalid: false,
		group: 28,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "igcfin",
		name: "Average gross cash farm income per farm",
		description:
			"For farms not participating in government programs, gross cash farm income is the total amount of cash received by the farm operation from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 90,
		is_invalid: false,
		group: 21,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "evlvpur",
		name: "Livestock purchases",
		description:
			"The total amount paid for livestock and poultry including commission, yardage, insurance and other associated fees. Breeding livestock treated as a depreciable capital is not included.",
		sequence: 90,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "fnw",
		name: "Total operator household net worth: Farm",
		description:
			"The farm operator's household share of farm business net worth (farm business assets minus farm business liabilities).",
		sequence: 90,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "antot",
		name: "Assets: Non-current",
		description:
			"Non-current assets are comprised of working assets that support the production process and farm real estate.",
		sequence: 100,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evfeed",
		name: "Feed",
		description:
			"Amount paid by the farm operation for all feed grains, hay, forages, mixed or formula feeds, concentrates, supplements, premixes, salt, minerals, animal byproducts, and all other feed additives and ingredients.",
		sequence: 100,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "froenum",
		name: "Operating expense ratio",
		description:
			"The operating expense ratio equals cash operating expenses divided by gross cash income of the farm business. This ratio measures the extent to which the cash income generated by the business is absorbed by the annual costs of production. The lower the ratio, the more effective the farm operation is in generating returns.",
		sequence: 100,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "incfi",
		name: "Average net cash farm income per farm",
		description: "For all farms, net cash farm income less cash expenses.",
		sequence: 100,
		is_invalid: false,
		group: 22,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "otherpay1",
		name: "Average government payment per participating farm",
		description:
			"Other government program payments received by other payment program participants.",
		sequence: 100,
		is_invalid: false,
		group: 29,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "opoc3",
		name: "Operator occupation: Retired from farming",
		description:
			"For most years, this is the share of principal farm operators reporting that they are retired from farming. In 1996, 1998-2001, and 2012 it is the share of farm of principal farm operators retired in general, not just from farming.",
		sequence: 100,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "drcnum75",
		name: "Repayment capacity use (7.5%)",
		description:
			"The ratio of actual debt to maximum debt repayment capacity measures the extent of use of potential credit repayment ability.  Calculated assuming 7.5 percent interest rate.",
		sequence: 100,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Percent",
	},
	{
		id: "nfnw",
		name: "Total operator household net worth: Non-farm",
		description:
			"Calculated as non-farm assets of the farm operator household minus non-farm debt.",
		sequence: 100,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Operator Household Balance Sheet",
		unit: "Dollars per HH",
	},
	{
		id: "aninvest",
		name: "Assets: Investment in cooperatives",
		description:
			"Estimated market value of all stock in the Farm Credit System and other farm cooperatives.",
		sequence: 110,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evloth",
		name: "Other livestock-related",
		description:
			"Amount paid by the farm operation during the calendar year for livestock leasing; custom feed processing, grinding or mixing of feed; bedding, litter, or straw; pasturing, grazing or custom feeding, veterinarian services or supplies, amount spent for sprays, dips, dusts or any other chemicals, sheep sheering, horse-shoeing, removal of dead animals, branding, artificial insemination and breeding fees, and performance testing.",
		sequence: 110,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "drcnum10",
		name: "Repayment capacity use (10%)",
		description:
			"The ratio of actual debt to maximum debt repayment capacity measures the extent of use of potential credit repayment ability.  Calculated assuming 10 percent interest rate.",
		sequence: 110,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Percent",
	},
	{
		id: "incfig",
		name: "Average net cash farm income per farm",
		description:
			"For all farms participating in any government programs, net cash farm income is gross cash income less cash expenses.",
		sequence: 110,
		is_invalid: false,
		group: 23,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "freconum",
		name: "Economic cost-to-output ratio",
		description:
			"Economic costs are calculated as total cash costs plus an allowance for depreciation, along with an imputed return to management and to unpaid labor of the operator and family labor.  The ratio is calculated as total economic costs divided by gross farm income.",
		sequence: 110,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Financial Ratios",
		unit: "Percent",
	},
	{
		id: "oped1",
		name: "Operator education: Less than high school",
		description:
			"The share of farm operators in the report column that did not complete high school",
		sequence: 110,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "igcfidp",
		name: "Average gross cash farm income per participating farm",
		description:
			"Gross cash income for farms participating in direct payment programs. Gross cash income is the total amount of cash received by the farm operations from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 110,
		is_invalid: false,
		group: 30,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "evseedp",
		name: "Seed and plants",
		description:
			"Expenses for purchases of seeds, plants, and related expenses such as seed cleaning, inoculation, rooting hormones, bagging, germinating, and delinting",
		sequence: 120,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "dtot",
		name: "Farm liabilities",
		description:
			"Total liabilities are composed of any monetary obligations of the farm operation on December 31. The amount reported includes principal due and any unpaid interest.  Debts for nonfarm purposes, even if farm or ranch assets are used as collateral, are excluded.",
		sequence: 120,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "anreale",
		name: "Assets: Land and buildings",
		description:
			"Estimated market value of all land and buildings owned by the farm operation.  Any other dwellings, such as those provided to hired labor, are also included if owned by the operation and located on the farm.",
		sequence: 120,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "oped2",
		name: "Operator education: Completed high school",
		description:
			"The share of farm operators in the report column that completed high school",
		sequence: 120,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "igcficcp",
		name: "Average gross cash farm income per participating farm",
		description:
			"Gross cash income for farms participating in countercyclical-type programs. Gross cash income is the total amount of cash received by the farm operations from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 120,
		is_invalid: false,
		group: 31,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "incfin",
		name: "Average net cash farm income per farm",
		description:
			"For farms not participating in any government programs, net cash farm income is gross cash income less cash expenses.",
		sequence: 120,
		is_invalid: false,
		group: 24,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "evfertc",
		name: "Fertilizer and chemicals",
		description:
			"Amount the farm operation paid for commercial fertilizers, lime and soil conditioners, pesticides, insecticides, herbicides, fungicides, defoliants, nematicides, fumigants, growth regulators, and rodenticides used on crops, pasture, acreage idled under government programs, seeds, crop storage buildings or seed beds.",
		sequence: 130,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "oped3",
		name: "Operator education: Some college",
		description:
			"The share of farm operators in the report column that completed some college (less than 4 years).",
		sequence: 130,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "infi",
		name: "Net farm income",
		description:
			"Net farm income indicates the profit or loss associated with current production. It represents the return (both monetary and nonmonetary) to farm operators for their labor, management and capital, after all production expenses have been paid (that is, gross farm income minus production expenses). It includes net income from farm production as well as net income attributed to the rental value of farm dwellings, the value of commodities consumed on the farm, depreciation, and inventory changes.",
		sequence: 130,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Debt Repayment Capacity",
		unit: "Dollars per farm",
	},
	{
		id: "igcfimlb",
		name: "Average gross cash farm income per participating farm",
		description:
			"Gross cash income for farms participating in marketing loan benefit programs. Gross cash income is the total amount of cash received by the farm operations from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 130,
		is_invalid: false,
		group: 32,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "oped4",
		name: "Operator education: Completed 4 years or more of college",
		description:
			"The share of farm operators in the report column that completed 4 years or more of college.",
		sequence: 140,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "anequip",
		name: "Assets: Farm equipment",
		description:
			"Estimated market value of the farm share of trucks, cars, tractors, machinery, tools, equipment and implements owned by the operation.",
		sequence: 140,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evutil",
		name: "Utilities",
		description:
			"Farm operations' share of expenses for electricity, telephone, and water including charges for irrigation water and electricity.",
		sequence: 140,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "igcficnsv",
		name: "Average gross cash farm income per participating farm",
		description:
			"Gross cash income for farms participating in conservation programs. Gross cash income is the total amount of cash received by the farm operations from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 140,
		is_invalid: false,
		group: 33,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "anbreed",
		name: "Assets: Breeding animals",
		description:
			"Estimated market value of all livestock animals held for breeding purposes.",
		sequence: 150,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evlabor",
		name: "Labor",
		description:
			'Expenses for contract and hired labor engaged in "agricultural work" during the calendar year.  Total cash wages include bonuses for all hired workers(including paid family members) and employees\' share of social security taxes.  Costs associated with fringe benefits such as insurance, pensions, workers compensation, and unemployment compensation are also included in labor expense.  Wages paid to operators that are not hired managers are excluded.',
		sequence: 150,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "ophr1",
		name: "Operator hours worked annually on farm: Less than 500",
		description:
			"The share of farm operators in the report column that worked less than 500 hours on the farm",
		sequence: 150,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "igcfioth",
		name: "Average gross cash farm income per participating farm",
		description:
			"Gross cash income for farms participating in other types of programs. Gross cash income is the total amount of cash received by the farm operations from the sale of agricultural products, services rendered, or government payments received during a given calendar year.",
		sequence: 150,
		is_invalid: false,
		group: 34,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "evfuelo",
		name: "Fuels and oils",
		description:
			"Farm share of the operations' purchases of diesel, gasoline, liquid petroleum, natural gas, other fuels (kerosene, coal, wood), and motor oils and fluids. Includes fuels used for heating farm buildings and offices, drying or curing crops, and all machinery and equipment (including irrigation pumps).",
		sequence: 160,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "incfidp",
		name: "Average net cash farm income per participating farm",
		description:
			"Net cash farm income for farms participating direct payment programs. Net cash farm income is gross cash farm income less cash expenses.",
		sequence: 160,
		is_invalid: false,
		group: 35,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "dtot",
		name: "Farm liabilities",
		description:
			"Total liabilities are composed of any monetary obligations of the farm operation on December 31. The amount reported includes principal due and any unpaid interest.  Debts for nonfarm purposes, even if farm or ranch assets are used as collateral, are excluded.",
		sequence: 160,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "ophr2",
		name: "Operator hours worked annually on farm: 500 to 999",
		description:
			"The share of farm operators in the report column that worked between 500 and 999 hours on the farm",
		sequence: 160,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "ophr3",
		name: "Operator hours worked annually on farm: 1,000 to 1,999",
		description:
			"The share of farm operators in the report column that worked between 1000 and 1,999 hours on the farm",
		sequence: 170,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "incficcp",
		name: "Average net cash farm income per participating farm",
		description:
			"Net cash income for farms participating countercyclical-type programs. Net cash farm income is gross cash farm income less cash expenses.",
		sequence: 170,
		is_invalid: false,
		group: 36,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "lctot",
		name: "Liabilities: Current",
		description:
			"Current liabilities are the debts a farm business owes which must be paid within one year.",
		sequence: 170,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evmainr",
		name: "Repairs and maintenance",
		description:
			"Amount paid by the operation for repairs and maintenance of motor vehicles, machinery and equipment, irrigation and frost protection equipment, farm buildings, the operator's dwelling, and any other labor dwellings, fencing, soil conservation structures, drainage structures, and any other farm or ranch structures (corrals, feedlots, feeding floors).",
		sequence: 170,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "dshort",
		name: "Liabilities: Notes payable within one year",
		description:
			"The amount of loans outstanding on December 31 that are due for full repayment within one year.",
		sequence: 180,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "evcwork",
		name: "Machine-hire and custom work",
		description:
			"Amount spent by the operation for custom hauling and other custom work such as land tillage, planting or seeding, harvesting, and soil testing.  Custom work is defined as work preformed by machines and labor hired as a unit.",
		sequence: 180,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "incfimlb",
		name: "Average net cash farm income per participating farm",
		description:
			"Net cash farm income for farms participating marketing loan benefit programs. Net cash farm income is gross cash farm income less cash expenses.",
		sequence: 180,
		is_invalid: false,
		group: 37,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "ophr4",
		name: "Operator hours worked annually on farm: 2,000 or more",
		description:
			"The share of farm operators in the report column that worked 2,000 hours or more on the farm.",
		sequence: 180,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Structural Characteristics",
		unit: "Percent of farms",
	},
	{
		id: "evoth",
		name: "Other variable expenses",
		description:
			"Includes supplies, motor vehicle registration fees, transportation and storage, and all other general business expenses (for example, fees paid to accountants or attorneys, registration of purebred animals, travel expenses, postage, and magazine subscriptions).",
		sequence: 190,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "incficnsv",
		name: "Average net cash farm income per participating farm",
		description:
			"Net cash income for farms participating conservation programs. Net cash farm income is gross cash farm income less cash expenses.",
		sequence: 190,
		is_invalid: false,
		group: 38,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "lcterm",
		name: "Liabilities: Current portion of term debt",
		description:
			"The current portion of long-term debt is the amount of principal that will be due within one year of the date of the balance sheet.",
		sequence: 190,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "incfioth",
		name: "Average net cash farm income per participating farm",
		description:
			"Net cash farm income for farms participating conservation programs. Net cash farm income is gross cash farm income less cash expenses.",
		sequence: 200,
		is_invalid: false,
		group: 39,
		level: 1,
		report: "Government Payments",
		unit: "Dollars",
	},
	{
		id: "lcint",
		name: "Liabilities: Accrued interest",
		description:
			"Estimated as the amount of interest that has accumulated since the previous interest payment.",
		sequence: 200,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "eftot",
		name: "Fixed expenses",
		description:
			"Represents costs incurred by the farm operation during the calendar year, even when there is no production.",
		sequence: 200,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "lcpay",
		name: "Liabilities: Accounts payable",
		description:
			"The obligation that the farm business owes to its creditors for buying goods or services.   It is the unpaid invoices, bills, or statements for goods or services rendered by outside contractors, vendors or suppliers.",
		sequence: 210,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "eftaxes",
		name: "Real estate and property taxes",
		description:
			"Expenses for taxes on farm land, buildings, capital improvements, machines, livestock, and other property.  Includes all taxes paid during the calendar year even though they may have been levied in another year.",
		sequence: 210,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "lntot",
		name: "Liabilities: Noncurrent",
		description:
			"Money owed by the farm business for a period one year or more in the future.",
		sequence: 220,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "efint",
		name: "Interest",
		description:
			"Amount paid by the farm operation for interest on farm business loans and mortgages, land contracts, and other farm loans secured by real estate, finance charges for operating loans, machinery and equipment loans, or any other interest on non-real estate loans.",
		sequence: 220,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "lnnreale",
		name: "Liabilities: Non-real estate",
		description:
			"The amount of debt owed by the farm business for non-real estate loans.",
		sequence: 230,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "efins",
		name: "Insurance premiums",
		description:
			"Amount spent by the farm operation for Federal Crop Insurance, and the farm share of motor vehicle, liability, and blanket policies which provide more than one year's coverage.",
		sequence: 230,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "efrent",
		name: "Rent and lease payments",
		description:
			"Expenses for land rental (including Public Industrial Grazing Association land), all vehicles, tractors, farm machinery, equipment, and structures leased.",
		sequence: 240,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "lnreale",
		name: "Liabilities: Real estate",
		description:
			"The amount of debt owed by the farm business for real estate loans.",
		sequence: 240,
		is_invalid: false,
		group: null,
		level: 3,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "netw",
		name: "Farm equity",
		description:
			"Total farm business assets minus farm business liabilities on December 31.",
		sequence: 250,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Balance Sheet",
		unit: "Dollars per farm",
	},
	{
		id: "incfi",
		name: "Net cash farm income",
		description:
			"This measure indicates the amount of net cash earnings from all business sources that a farm generates during the year.  These funds can be used to repay principal on indebtedness, purchase new machinery or equipment, expand the farm business, or pay for family consumption or other obligations.",
		sequence: 250,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "inmon",
		name: "Nonmoney income",
		description:
			"An estimated value of items produced and consumed on the farm, and the imputed rental value of farm dwellings.",
		sequence: 260,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "ivalinv",
		name: "Value of inventory change",
		description:
			"The change in the market value of all crops, livestock, or purchased inputs from January 1 of the calendar to December 31.",
		sequence: 270,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "endepr",
		name: "Depreciation",
		description:
			"An allocation of the portion of the original cost of a capital asset to each of the estimated years in which the asset will be used.  The type of depreciation reported on the survey typically resembles the figure reported on tax returns.",
		sequence: 280,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "enben",
		name: "Labor, non-cash benefits",
		description:
			"Includes an estimate of the value of housing or lodging provided to workers, meals, fuel, vehicles, utilities, or payment in kind. An estimate of the value of products produced and consumed on the farm is provided by the survey respondent. The imputed rental value of farm dwellings is calculated for dwellings located on the farm and is based on rent-to-value ratios for different value ranges of the dwelling.",
		sequence: 290,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "breedingadj",
		name: "Adjusted breeding livestock income",
		description:
			"The amount of unrecovered investment in breeding livestock upon sale, reflecting the difference between gross proceeds from the sale and the recognized gain after accounting for investment costs.",
		sequence: 300,
		is_invalid: false,
		group: null,
		level: 2,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
	{
		id: "infi",
		name: "Net farm income",
		description:
			"Net farm income indicates the profit or loss associated with current production. It represents the return (both monetary and nonmonetary) to farm operators for their labor, management and capital after all production expenses have been paid (that is, gross farm income minus production expenses). It includes net income from farm production as well as net income attributed to the rental value of farm dwellings, the value of commodities consumed on the farm, depreciation, and inventory changes.",
		sequence: 310,
		is_invalid: false,
		group: null,
		level: 1,
		report: "Farm Business Income Statement",
		unit: "Dollars per farm",
	},
];
